[book]
title = "TerminalOS"
authors = ["Pandit Dhamdhere"]
description = "The AI-native terminal for developers"
language = "en"
src = "docs/src"

[build]
build-dir = "docs/book"

[output.html]
site-url = "https://panditdhamdhere.github.io/TerminalOS/"
git-repository-url = "https://github.com/panditdhamdhere/TerminalOS"
edit-url-template = "https://github.com/panditdhamdhere/TerminalOS/edit/main/{path}"
